name: 🆕🎮 New Extension Request
description: Suggest an idea and show your creativity to add new extension code.
title: "[New Extension]: "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out your new extension issue
  - type: textarea
    id: new-extension
    attributes:
      label: 🎮 Extension Request
      description: Describe the extension logic and also give a brief about the features of the extension
      placeholder: add all necessary details required for your new extension
      value: "Extension logic and basic description"
    validations:
      required: true
  - type: textarea
    id: features
    attributes:
      label: Point down the features
      description: think about your the feature your extension will have.
      placeholder: Please include a summary, also include relevant motivation and context. 
      value: "Extension points"
    validations:
      required: true
  - type: dropdown
    id: contribution
    attributes:
      label: Select program in which you are contributing
      multiple: true
      options:
        - IWOC2024
        - GSSoC24
        - hacktoberfest
        - GSSoC23
        - Other
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [CODE OF CONDUCT](https://github.com/Sulagna-Dutta-Roy/GGExtensions/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I follow [CONTRIBUTING GUIDELINE](https://github.com/Sulagna-Dutta-Roy/GGExtensions/blob/master/README.md) of this project.
          required: true
